spring:
  devtools:
     livereload:
        enabled: true
     restart:
        enabled: false 
         
  datasource:
     url: jdbc:h2:tcp://localhost/~/jpashop
     username: sa
     password: 123
     driver-class-name: org.h2.Driver
      
  jpa:
     hibernate:
        ddl-auto: create 
     properties:
        hibernate:
#           show_sql: true # hibernate가 생성하는 SQL을 콘솔에 출력, 실제 운영에서는 사용X
           format_sql: true      
            
logging:
  level:
     org.hibernate.SQL: debug # hibernate가 생성하는 SQL이 로거를 통해 출력
     org.hibernate.type: trace